export default {
    AiServiceType: {
        "VIP detected": 0,
        "Black list detected": 1,
        "Loitering detected": 2,
        "Break-in detected": 3,
        "Crow detected": 4,
        "Weapon detected": 5,
        "Behavior detected": 6,
        "System": 7,
        "Fire Smoke": 8,
        "Line Crossing": 9,
        "Person Area Detection": 10,
        "Person Area Intrusion": 11,
        "Face Area Detection": 12,
        "Face Area Intrusion": 13,
        "Person Line Crossing": 14,
        "Vehicle Area Detection": 15,
        "Weapon Area Detection": 16,
        "Fire Area Detection": 17,
        "Vehicle Area Intrustion": 18,
        "Vehicle Line Crossing": 19,
    },
}
