export default {
    AlertScriptType: {
        "All": -1,
        "Mobile Notification": 0,
        "Dashboard Notification": 1,
        "Send email": 2,
    },
    AlertLevel: {
        "All": -1,
        1: "High",
        2: "Medium",
        3: "Low",
    },
    AlertType: {
        "All": -1,
        0: "VIP detected",
        1: "Black list detected",
        2: "Loitering detected",
        3: "Break-in detected",
        4: "Crow detected",
        5: "Weapon detected",
        6: "Behavior detected",
        7: "System",
        8: "FireSmoke",
        9: "LineCrossing",
        10: "Person Area Detection",
        11: "Person Area Intrusion",
        12: "Face Area Detection",
        13: "Face Area Intrusion",
        14: "Person Line Crossing",
        15: "Vehicle Area Detection",
        16: "Weapon Area Detection",
        17: "Fire Area Detection",
        18: "Vehicle Area Intrustion",
        19: "Vehicle Line Crossing",
    },

    AlertTypeEnums: {
        "All": -1,
        // "VIP detected": 0,
        // "Black list detected": 1,
        // "Loitering detected": 2,
        // "Break-in detected": 3,
        // "Crow detected": 4,
        // "Weapon detected": 5,
        // "Behavior detected": 6,
        // "System": 7,
        // "Fire Smoke": 8,
        // "Line Crossing": 9,
        "Person Area Detection": 10,
        "Person Area Intrusion": 11,
        "Face Area Detection": 12,
        "Face Area Intrusion": 13,
        "Person Line Crossing": 14,
        "Vehicle Area Detection": 15,
        "Weapon Area Detection": 16,
        "Fire Area Detection": 17,
        "Vehicle Area Intrustion": 18,
        "Vehicle Line Crossing": 19,
    }
}